skip_commits:
  files:
    - CHANGES
    - ICHANGES
    - etc/
    - geneweb.opam
    - .gitignore
    - hd/
    - INSTALL
    - LICENSE
    - README.md
    - man/
    - .travis.yml

platform:
  - x86

environment:
  CYG_ROOT: C:/cygwin
  CYG_BASH: '%CYG_ROOT%/bin/bash -lc'
  OPAM_PACKAGES: 'benchmark camlp5 cppo dune markup num ounit stdlib-shims zarith'

install:
  - 'set OPAMYES=1'
  - 'set PATH=%PATH%;%CYG_ROOT%\usr\i686-w64-mingw32\sys-root\mingw\bin'
  - '%CYG_ROOT%\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup -P rsync -P patch -P diffutils -P unzip -P m4 -P mingw64-i686-gcc-core -P mingw64-i686-gmp'
  - '%CYG_BASH% "curl -fsSL -o opam32.tar.xz https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam32.tar.xz"'
  - '%CYG_BASH% "tar -xf opam32.tar.xz && opam32/install.sh"'
  - '%CYG_BASH% "opam init -a mingw https://github.com/fdopen/opam-repository-mingw.git#opam2 -c 4.09.0+mingw32c --disable-sandboxing"'
  - '%CYG_BASH% "opam install ${OPAM_PACKAGES}"'
  - '%CYG_BASH% "eval $(ocaml-env cygwin)"'

build_script:
  - '%CYG_BASH% "cd ${APPVEYOR_BUILD_FOLDER} && ./configure --gwdb1 && make test bench distrib"'
  - '%CYG_BASH% "cd ${APPVEYOR_BUILD_FOLDER} && ./configure --gwdb1 --sosa-num && make clean test bench"'
  - '%CYG_BASH% "cd ${APPVEYOR_BUILD_FOLDER} && ./configure --gwdb1 --sosa-zarith && make clean test bench "'
