name: GeneWeb CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - '**/*.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'
  push:
    branches:
      - master
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - '**/*.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'

env:
  OPAMYES: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-latest]
        ocaml-compiler: [4.14.2, 5.3.0]
        setup-version: [v3]
        include:
          - os: ubuntu-22.04
            ocaml-compiler: 4.08.1
            setup-version: v2
          - os: macos-13
            ocaml-compiler: 4.08.1
            setup-version: v2
          - os: windows-latest
            ocaml-compiler: 4.08.1
            setup-version: v2

    outputs:
      total_matrix_jobs: ${{ strategy.job-total || 0 }}
      metric: ${{ steps.collect-metrics.outputs.metric }}

    env:
      FMT_CI: ${{ matrix.os == 'ubuntu-24.04' && matrix.ocaml-compiler == '4.14.2' && matrix.setup-version == 'v3' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Start Build Timer
        uses: ./.github/actions/ci-utils
        with:
          command: start-timer

      - name: Cache Opam dependencies (Unix)
        id: cache-opam-unix
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: unix-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}-${{ hashFiles('*.opam') }}-cache
          restore-keys: unix-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}

      - name: Cache Opam dependencies (Windows)
        id: cache-opam-windows
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: D:\.opam
          key: windows-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}-${{ hashFiles('*.opam') }}-cache
          restore-keys: windows-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}

      - name: Setup Ocaml with v2
        if: matrix.setup-version == 'v2'
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          
      - name: Setup Ocaml with v3
        if: matrix.setup-version == 'v3'
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Pin camlp5 and not-ocamlfind without installing
        if: matrix.setup-version == 'v3'
        run: |
          opam pin add --no-action camlp5 https://github.com/camlp5/camlp5.git
          opam pin add --no-action not-ocamlfind https://github.com/chetmurthy/not-ocamlfind.git

      - name: Install Geneweb dependencies
        run: |
          opam install . --deps-only ${{ env.FMT_CI == 'true' && '--with-test' || '' }}

      - name: Install ancient dependency for Unix
        if: ${{ runner.os != 'Windows' }}
        run: opam pin ancient https://github.com/OCamlPro/ocaml-ancient.git

      - name: Install dependencies for v2 test environments
        if: matrix.setup-version == 'v2'
        run: opam install pcre
        continue-on-error: true

      - name: Run Camlp5 test suite
        run: |
          # Ensure OPAM environment is properly set up
          eval $(opam env)
          
          echo "==== Environment Info ===="
          echo "OCaml version: $(ocaml -version 2>/dev/null || echo 'Not found')"
          echo "OPAM version: $(opam --version)"
          echo "OPAM switch: $(opam switch show)"
          echo "OS: $RUNNER_OS"
          echo "Setup version: ${{ matrix.setup-version }}"
          echo "=========================="
          
          # WINDOWS-SPECIFIC APPROACH
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "===== WINDOWS PATH DETECTION ====="
            
            # Check for ocamlfind
            which ocamlfind || echo "WARNING: ocamlfind not found in PATH"
            
            # Find camlp5 directory - try both build and sources paths
            CAMLP5_BUILD_DIR=""
            CAMLP5_BUILD_DIR=$(find "D:\a\geneweb\geneweb\_opam\.opam-switch\build" -type d -name "camlp5.*" | sort -V | tail -n 1)
            echo "Found camlp5 build dir: $CAMLP5_BUILD_DIR"
            
            if [ -d "$CAMLP5_BUILD_DIR" ]; then
              echo "Directory exists"
              if [ -d "$CAMLP5_BUILD_DIR/testsuite" ]; then
                echo "Testsuite directory exists"
                echo "Found Camlp5 build directory: $CAMLP5_BUILD_DIR"
                
                # Fix the LAUNCH script issue
                echo "Fixing LAUNCH script issue..."
                
                # First, let's see if we can find camlp5-buildscripts directory
                echo "Looking for camlp5-buildscripts directory..."
                BUILDSCRIPTS_DIR=$(find "D:\a\geneweb\geneweb\_opam" -type d -name "camlp5-buildscripts" | head -n 1)
                echo "Buildscripts dir search result: $BUILDSCRIPTS_DIR"
                
                # Alternative: look directly for the LAUNCH script
                echo "Looking for LAUNCH script directly..."
                LAUNCH_DIRECT=$(find "D:\a\geneweb\geneweb\_opam" -name "LAUNCH" | head -n 1)
                echo "Direct LAUNCH search result: $LAUNCH_DIRECT"
                
                # Find the LAUNCH script location
                echo "Looking for LAUNCH script in lib directory..."
                LAUNCH_FILES=$(find "D:\a\geneweb\geneweb\_opam\lib" -name "LAUNCH" 2>/dev/null || echo "No LAUNCH files found")
                echo "All LAUNCH files found: $LAUNCH_FILES"
                
                echo "Filtering for camlp5-buildscripts..."
                LAUNCH_SCRIPT=$(echo "$LAUNCH_FILES" | grep "camlp5-buildscripts" || echo "")
                echo "Filtered LAUNCH script: $LAUNCH_SCRIPT"
                
                # If we didn't find it via grep, use the direct result
                if [ -z "$LAUNCH_SCRIPT" ] && [ -n "$LAUNCH_DIRECT" ]; then
                  LAUNCH_SCRIPT="$LAUNCH_DIRECT"
                  echo "Using directly found LAUNCH script: $LAUNCH_SCRIPT"
                fi
                
                if [ -n "$LAUNCH_SCRIPT" ] && [ -f "$LAUNCH_SCRIPT" ]; then
                  echo "LAUNCH script found and is a file"
                  echo "Original LAUNCH script: $LAUNCH_SCRIPT"
                  echo "File permissions:"
                  ls -la "$LAUNCH_SCRIPT"
                  
                  echo "File contents (first few lines):"
                  head -n 5 "$LAUNCH_SCRIPT" || echo "Could not read file"
                  
                  # Try to create a copy with .exe extension
                  echo "Creating copy with .exe extension..."
                  cp -v "$LAUNCH_SCRIPT" "${LAUNCH_SCRIPT}.exe" || echo "Failed to copy file"
                  
                  if [ -f "${LAUNCH_SCRIPT}.exe" ]; then
                    echo "Successfully created .exe copy"
                    ls -la "${LAUNCH_SCRIPT}.exe"
                  else
                    echo "Failed to create .exe copy"
                  fi
                  
                  # Now let's try creating the wrapper
                  echo "Creating wrapper in testsuite directory..."
                  cd "$CAMLP5_BUILD_DIR/testsuite" || echo "Failed to change directory"
                  
                  echo "Current directory: $(pwd)"
                  echo "Creating camlp5-buildscripts directory..."
                  mkdir -p camlp5-buildscripts || echo "Failed to create directory"
                  
                  if [ -d "camlp5-buildscripts" ]; then
                    echo "Successfully created directory"
                    
                    # Create the wrapper script
                    echo "Creating LAUNCH wrapper script..."
                    echo '#!/bin/bash' > camlp5-buildscripts/LAUNCH
                    echo "\"$LAUNCH_SCRIPT\" \"\$@\"" >> camlp5-buildscripts/LAUNCH
                    
                    echo "Wrapper script contents:"
                    cat camlp5-buildscripts/LAUNCH
                    
                    echo "Making wrapper executable..."
                    chmod +x camlp5-buildscripts/LAUNCH || echo "Failed to make executable"
                    
                    # Create .exe version
                    echo "Creating .exe version of wrapper..."
                    cp camlp5-buildscripts/LAUNCH camlp5-buildscripts/LAUNCH.exe || echo "Failed to create .exe wrapper"
                    chmod +x camlp5-buildscripts/LAUNCH.exe || echo "Failed to make .exe wrapper executable"
                    
                    ls -la camlp5-buildscripts/
                    
                    # Update PATH
                    echo "Original PATH: $PATH"
                    export PATH="$PWD/camlp5-buildscripts:$PATH"
                    echo "Updated PATH: $PATH"
                    
                    echo "Testing wrapper script..."
                    if [ -x "camlp5-buildscripts/LAUNCH" ]; then
                      camlp5-buildscripts/LAUNCH echo "Wrapper test" || echo "Wrapper test failed"
                    fi
                    
                    # Try to find mkcamlp5
                    echo "Looking for mkcamlp5..."
                    which mkcamlp5 || echo "mkcamlp5 not found in PATH"
                    find "D:\a\geneweb\geneweb\_opam" -name "mkcamlp5*" || echo "No mkcamlp5 found"
                    
                    echo "Running Camlp5 test suite with fixed LAUNCH script..."
                    echo "===== BEGIN TEST OUTPUT ====="
                    # Just run a simple single target first to test
                    make tools/ROUNDTRIP-pa_r-pr_r.byte || echo "First target failed"
                    echo "===== END TEST OUTPUT ====="
                  else
                    echo "Failed to create wrapper directory"
                    echo "Skipping test suite"
                  fi
                else
                  echo "LAUNCH script not found or not a file"
                  if [ -n "$BUILDSCRIPTS_DIR" ]; then
                    echo "Contents of buildscripts directory:"
                    ls -la "$BUILDSCRIPTS_DIR"
                  fi
                  echo "Skipping tests for Windows due to missing LAUNCH script"
                fi
              else
                echo "Testsuite directory does not exist"
                echo "Contents of Camlp5 directory:"
                ls -la "$CAMLP5_BUILD_DIR"
                echo "Skipping tests for Windows"
              fi
            else
              echo "Directory does not exist"
              echo "Available Camlp5 directories:"
              find "D:\a\geneweb\geneweb\_opam" -name "camlp5*" -type d | grep -v "lib"
              echo "Skipping tests for Windows"
            fi
          # UNIX APPROACH - keep unchanged
          else
            echo "===== UNIX PATH DETECTION ====="
            
            # Check for ocamlfind
            which ocamlfind || echo "WARNING: ocamlfind not found in PATH"
            
            # Get OPAM prefix
            OPAM_PREFIX=$(opam var prefix)
            echo "OPAM prefix: $OPAM_PREFIX"
            
            # Try different paths based on version
            if [ "${{ matrix.setup-version }}" == "v3" ]; then
              # v3 path is known to work
              CAMLP5_DIR=$(find "$OPAM_PREFIX/.opam-switch/build" -type d -name "camlp5.*" 2>/dev/null | sort -V | tail -n 1)
            else
              # v2 might need to look in sources
              CAMLP5_DIR=$(find "$OPAM_PREFIX/.opam-switch/sources" -type d -name "camlp5.*" 2>/dev/null | sort -V | tail -n 1)
            fi
            
            if [ -d "$CAMLP5_DIR" ] && [ -d "$CAMLP5_DIR/testsuite" ]; then
              echo "Found Camlp5 directory: $CAMLP5_DIR"
              
              echo "Running Camlp5 test suite on Unix..."
              cd "$CAMLP5_DIR/testsuite"
              
              echo "===== BEGIN TEST OUTPUT ====="
              if [ "${{ matrix.setup-version }}" == "v3" ]; then
                make -k all-tests || echo "Tests completed with some errors, but continuing build"
              else
                make all-tests || echo "Tests completed with some errors, but continuing build"
              fi
              echo "===== END TEST OUTPUT ====="
            else
              echo "Camlp5 testsuite directory not found"
              echo "Available Camlp5 directories:"
              find "$OPAM_PREFIX" -name "camlp5*" -type d | grep -v "lib"
              echo "Skipping tests"
            fi
          fi
        shell: bash
        continue-on-error: true

      - name: Configure
        run: opam exec -- ocaml ./configure.ml --sosa-zarith

      - name: Build Geneweb
        run: opam exec -- make ${{ env.FMT_CI == 'true' && 'fmt ci' || 'build' }} distrib

      - name: "Test Geneweb daemon with --cache-in-memory"
        if: ${{ runner.os != 'Windows' }}
        run: |
          output=$(distribution/gw/gwd -cache-in-memory testing 2>&1)
          if echo "$output" | grep -q "Caching database testing in memory"; then
            echo "Caching message found, test passed."
            exit 0
          else
            echo "Caching message not found, test failed."
            exit 1
          fi

      - name: Collect Build Metrics
        id: collect-metrics
        uses: ./.github/actions/ci-utils
        with:
          command: collect-metrics
          os: ${{ matrix.os }}
          ocaml-version: ${{ matrix.ocaml-compiler }}
          cache-hit: ${{ runner.os != 'Windows' && steps.cache-opam-unix.outputs.cache-hit || steps.cache-opam-windows.outputs.cache-hit }}

  build-results:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Build Summary
        uses: ./.github/actions/ci-utils
        with:
          command: generate-summary
          total-builds: ${{ needs.build.outputs.total_matrix_jobs }}
