name: GeneWeb CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - '**/*.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'
  push:
    branches:
      - master
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - '**/*.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'

env:
  OPAMYES: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # v2 builds (legacy environments)

          # v3 builds (newer environments)

          - os: windows-latest
            ocaml-compiler: 5.3.0
            setup-version: v3

          - os: ubuntu-latest
            ocaml-compiler: 5.3.0
            setup-version: v3

          - os: macOS-latest
            ocaml-compiler: 5.3.0
            setup-version: v3

    outputs:
      total_matrix_jobs: ${{ strategy.job-total || 0 }}
      metric: ${{ steps.collect-metrics.outputs.metric }}

    env:
      FMT_CI: ${{ matrix.os == 'ubuntu-24.04' && matrix.ocaml-compiler == '4.14.2' && matrix.setup-version == 'v3' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Start Build Timer
        uses: ./.github/actions/ci-utils
        with:
          command: start-timer

      - name: Cache Opam dependencies (Unix)
        id: cache-opam-unix
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: unix-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}-${{ hashFiles('*.opam') }}-cache
          restore-keys: unix-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}

      - name: Cache Opam dependencies (Windows)
        id: cache-opam-windows
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: D:\.opam
          key: windows-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}-${{ hashFiles('*.opam') }}-cache
          restore-keys: windows-${{ matrix.ocaml-compiler }}-${{ env.FMT_CI == 'true' && 'with-test' || 'no-test' }}-${{ matrix.setup-version }}

      - name: Setup Ocaml with v2
        if: matrix.setup-version == 'v2'
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Setup Ocaml with v3
        if: matrix.setup-version == 'v3'
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Pin camlp5 and not-ocamlfind without installing
        run: |
          opam pin add --no-action camlp5 https://github.com/camlp5/camlp5.git#master
          opam pin add --no-action not-ocamlfind https://github.com/chetmurthy/not-ocamlfind.git#master

      - name: Install Geneweb dependencies
        run: opam install . --deps-only ${{ env.FMT_CI == 'true' && '--with-test' || '' }}

      - name: Install ancient dependency for Unix
        if: ${{ runner.os != 'Windows' }}
        run: opam pin ancient -y https://github.com/OCamlPro/ocaml-ancient.git

      - name: Configure
        run: opam exec -- ocaml ./configure.ml --sosa-zarith

      - name: Build Geneweb
        run: opam exec -- make ${{ env.FMT_CI == 'true' && 'fmt ci' || 'build' }} distrib

      - name: Display contents of Camlp5 config files
        if: always()
        run: |
          echo ===============================================================
          echo                     CAMLP5 CONFIG FILES
          echo ===============================================================
          
          for /f "tokens=*" %%f in ('dir "D:\a\geneweb\geneweb\_opam\.opam-switch\sources\camlp5\config" /b /a') do (
            echo ==================================================================
            echo   FILE: %%f
            echo ==================================================================
            type "D:\a\geneweb\geneweb\_opam\.opam-switch\sources\camlp5\config\%%f"
            echo.
          )
        shell: cmd
        continue-on-error: true

      - name: Archive Camlp5 config directory
        if: always()
        run: |
          mkdir -p camlp5-config
          xcopy /E /I /H /Y "D:\a\geneweb\geneweb\_opam\.opam-switch\sources\camlp5\config" "camlp5-config\"
        shell: cmd
        continue-on-error: true

      - name: Upload Camlp5 config directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: camlp5-config
          path: camlp5-config/
          retention-days: 3

      - name: Display Camlp5 META file
        if: always()
        run: |
          echo ==================================================================
          echo ===                    CAMLP5 META FILE                        ===
          echo ==================================================================
          type "D:\a\geneweb\geneweb\_opam\lib\camlp5\META" || echo "META file not found"
          echo.
        shell: cmd
        continue-on-error: true

      - name: Capture Camlp5 META file
        if: always()
        run: |
          mkdir -p camlp5-meta
          cp "D:\a\geneweb\geneweb\_opam\lib\camlp5\META" camlp5-meta/
        shell: bash
        continue-on-error: true

      - name: Upload Camlp5 META file as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: camlp5-meta-file
          path: camlp5-meta/
          retention-days: 3

      - name: "Test Geneweb daemon with --cache-in-memory"
        if: ${{ runner.os != 'Windows' }}
        run: |
          output=$(distribution/gw/gwd -cache-in-memory testing 2>&1)
          if echo "$output" | grep -q "Caching database testing in memory"; then
            echo "Caching message found, test passed."
            exit 0
          else
            echo "Caching message not found, test failed."
            exit 1
          fi

      - name: Collect Build Metrics
        id: collect-metrics
        uses: ./.github/actions/ci-utils
        with:
          command: collect-metrics
          os: ${{ matrix.os }}
          ocaml-version: ${{ matrix.ocaml-compiler }}
          cache-hit: ${{ runner.os != 'Windows' && steps.cache-opam-unix.outputs.cache-hit || steps.cache-opam-windows.outputs.cache-hit }}

  build-results:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Build Summary
        uses: ./.github/actions/ci-utils
        with:
          command: generate-summary
          total-builds: ${{ needs.build.outputs.total_matrix_jobs }}
