name: Build GeneWeb Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - 'CONTRIBUTING.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'README.md'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'
  pull_request:
    paths-ignore:
      - 'etc/**'
      - 'hd/**'
      - 'man/**'
      - 'CONTRIBUTING.md'
      - 'geneweb_colab.ipynb'
      - 'ICHANGES'
      - 'INSTALL'
      - 'LICENSE'
      - 'README.md'
      - 'CHANGES'
      - '.gitattributes'
      - '.gitignore'
      - '.git-blame-ignore-revs'
      - '.ocamlformat'
      - '.ocamlformat-ignore'
      - 'geneweb.iss'
      - 'geneweb.opam.template'

env:
  PLATFORMS: ${{ github.ref == 'refs/heads/master' && 'linux/arm64/v8,linux/amd64' || 'linux/amd64' }}
  IMAGE_NAME: "geneweb"
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/master' }}
  CACHE_FROM: type=gha,scope=${{ github.ref == 'refs/heads/master' && 'docker-build-master' || 'docker-build-pr' }}
  CACHE_TO: type=gha,scope=${{ github.ref == 'refs/heads/master' && 'docker-build-master' || 'docker-build-pr' }},mode=max

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 1

      - name: Generate Docker image metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,branch=master
            type=sha,prefix=,format=short
          labels: |
            org.opencontainers.image.title=GeneWeb
            org.opencontainers.image.description=Genealogy Software
            maintainer=${{ github.repository_owner }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
          driver-opts: |
            network=host
            image=moby/buildkit:latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: github.ref == 'refs/heads/master'

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref_name }}-
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/
          file: docker/Dockerfile
          target: container
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,scope=${{ github.ref_name }},mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            FAST_BUILD=${{ github.ref != 'refs/heads/master' && '1' || '0' }}
